# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f33592bf50a818f87cf50659de87ffbceea693aae174579080fe7c189e254b5eb0b50d845b379a3cd152dfadbc33a8b7749c5f913410096e0c68e8774e369e8

test:
  secret_key_base: 907e17273b56380379ad7151f664ccb287366f9608e45e9381520ae27b668b2ba28db3a8683f04fdf759c3397188e7a0744b04fe017396b9447d56b707b376d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
